using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace Nibo.SpaceJam.Models
{
    /// <summary>
    /// Base model data structure
    /// </summary>
    /// <typeparam name="TModel"></typeparam>
    public class BaseModel<TModel>
    {
        /// <summary>
        /// AutoGenerated ID
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }
    }
}
