//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nibo.SpaceJam.Infraestructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nibo.SpaceJam.Infraestructure.Resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_ModelId_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_ModelId_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id do registro.
        /// </summary>
        public static string OperationLogModel_ModelId_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_ModelId_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_ModelType_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_ModelType_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo modificado.
        /// </summary>
        public static string OperationLogModel_ModelType_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_ModelType_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto serializado em JSON.
        /// </summary>
        public static string OperationLogModel_NewState_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_NewState_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo estado.
        /// </summary>
        public static string OperationLogModel_NewState_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_NewState_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto serializado em JSON.
        /// </summary>
        public static string OperationLogModel_OldState_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_OldState_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado anterior.
        /// </summary>
        public static string OperationLogModel_OldState_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_OldState_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_OperationDate_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_OperationDate_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da operação.
        /// </summary>
        public static string OperationLogModel_OperationDate_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_OperationDate_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_OperationType_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_OperationType_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de operação.
        /// </summary>
        public static string OperationLogModel_OperationType_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_OperationType_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_Origin_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_Origin_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem.
        /// </summary>
        public static string OperationLogModel_Origin_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_Origin_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_UserAddress_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_UserAddress_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP do responsável.
        /// </summary>
        public static string OperationLogModel_UserAddress_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_UserAddress_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OperationLogModel_UserLogin_Display_Description {
            get {
                return ResourceManager.GetString("OperationLogModel_UserLogin_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável pela operação.
        /// </summary>
        public static string OperationLogModel_UserLogin_Display_Name {
            get {
                return ResourceManager.GetString("OperationLogModel_UserLogin_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TeamModel_Name_Display_Description {
            get {
                return ResourceManager.GetString("TeamModel_Name_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do time.
        /// </summary>
        public static string TeamModel_Name_Display_Name {
            get {
                return ResourceManager.GetString("TeamModel_Name_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time A.
        /// </summary>
        public static string TournamentFinalMatchModel_TeamA_Display_Name {
            get {
                return ResourceManager.GetString("TournamentFinalMatchModel_TeamA_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O time A precisa ser informado!.
        /// </summary>
        public static string TournamentFinalMatchModel_TeamA_Required {
            get {
                return ResourceManager.GetString("TournamentFinalMatchModel_TeamA_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time B.
        /// </summary>
        public static string TournamentFinalMatchModel_TeamB_Display_Name {
            get {
                return ResourceManager.GetString("TournamentFinalMatchModel_TeamB_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O time B precisa ser informado!.
        /// </summary>
        public static string TournamentFinalMatchModel_TeamB_Required {
            get {
                return ResourceManager.GetString("TournamentFinalMatchModel_TeamB_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentModel_Name_Display_Description {
            get {
                return ResourceManager.GetString("TournamentModel_Name_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do torneio.
        /// </summary>
        public static string TournamentModel_Name_Display_Name {
            get {
                return ResourceManager.GetString("TournamentModel_Name_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentModel_Stage_Display_Description {
            get {
                return ResourceManager.GetString("TournamentModel_Stage_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapa do torneio.
        /// </summary>
        public static string TournamentModel_Stage_Display_Name {
            get {
                return ResourceManager.GetString("TournamentModel_Stage_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyFour_Display_Description {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyFour_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ª chave.
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyFour_Display_Name {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyFour_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyOne_Display_Description {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyOne_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ª chave.
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyOne_Display_Name {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyOne_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyTree_Display_Description {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyTree_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3ª chave.
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyTree_Display_Name {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyTree_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyTwo_Display_Description {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyTwo_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ª chave.
        /// </summary>
        public static string TournamentQuarterFinalsMatchModel_KeyTwo_Display_Name {
            get {
                return ResourceManager.GetString("TournamentQuarterFinalsMatchModel_KeyTwo_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentResultModel_Final_Display_Description {
            get {
                return ResourceManager.GetString("TournamentResultModel_Final_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string TournamentResultModel_Final_Display_Name {
            get {
                return ResourceManager.GetString("TournamentResultModel_Final_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentResultModel_QuarterFinals_Display_Description {
            get {
                return ResourceManager.GetString("TournamentResultModel_QuarterFinals_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartas de final.
        /// </summary>
        public static string TournamentResultModel_QuarterFinals_Display_Name {
            get {
                return ResourceManager.GetString("TournamentResultModel_QuarterFinals_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentResultModel_SemiFinals_Display_Description {
            get {
                return ResourceManager.GetString("TournamentResultModel_SemiFinals_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi final.
        /// </summary>
        public static string TournamentResultModel_SemiFinals_Display_Name {
            get {
                return ResourceManager.GetString("TournamentResultModel_SemiFinals_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentResultModel_Tournament_Display_Description {
            get {
                return ResourceManager.GetString("TournamentResultModel_Tournament_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torneio.
        /// </summary>
        public static string TournamentResultModel_Tournament_Display_Name {
            get {
                return ResourceManager.GetString("TournamentResultModel_Tournament_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O torneio precisa ser informado para controlar os resultados!.
        /// </summary>
        public static string TournamentResultModel_Tournament_Required {
            get {
                return ResourceManager.GetString("TournamentResultModel_Tournament_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentResultModel_Winner_Display_Description {
            get {
                return ResourceManager.GetString("TournamentResultModel_Winner_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time vencedor.
        /// </summary>
        public static string TournamentResultModel_Winner_Display_Name {
            get {
                return ResourceManager.GetString("TournamentResultModel_Winner_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O vencedor do torneio precisa ser um time registrado na final!.
        /// </summary>
        public static string TournamentResultModel_Winner_Invalid {
            get {
                return ResourceManager.GetString("TournamentResultModel_Winner_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentSemiFinalsMatchModel_KeyOne_Display_Description {
            get {
                return ResourceManager.GetString("TournamentSemiFinalsMatchModel_KeyOne_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1ª Chave.
        /// </summary>
        public static string TournamentSemiFinalsMatchModel_KeyOne_Display_Name {
            get {
                return ResourceManager.GetString("TournamentSemiFinalsMatchModel_KeyOne_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TournamentSemiFinalsMatchModel_KeyTwo_Display_Description {
            get {
                return ResourceManager.GetString("TournamentSemiFinalsMatchModel_KeyTwo_Display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ª Chave.
        /// </summary>
        public static string TournamentSemiFinalsMatchModel_KeyTwo_Display_Name {
            get {
                return ResourceManager.GetString("TournamentSemiFinalsMatchModel_KeyTwo_Display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obrigatório!.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As chaves precisam ter no mínimo 2 times!.
        /// </summary>
        public static string Validation_TournamentMatchKeys_Minimum {
            get {
                return ResourceManager.GetString("Validation_TournamentMatchKeys_Minimum", resourceCulture);
            }
        }
    }
}
