//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nibo.SpaceJam.Infraestructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Services {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Services() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nibo.SpaceJam.Infraestructure.Resources.Services", typeof(Services).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível localizar o registro com o id informado!.
        /// </summary>
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um time cadastrado com este nome!.
        /// </summary>
        public static string TeamService_CreateOrUpdateAsync_Validation_UniqueTeamName {
            get {
                return ResourceManager.GetString("TeamService_CreateOrUpdateAsync_Validation_UniqueTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os times da final precisam ter participado da semi final!.
        /// </summary>
        public static string TournamentResultService_RegisterFinal_Validation_InvalidFinalTeam {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterFinal_Validation_InvalidFinalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os times da semi final precisam ser vencedores das quartas de final!.
        /// </summary>
        public static string TournamentResultService_RegisterFinal_Validation_InvalidSemiFinalTeam {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterFinal_Validation_InvalidSemiFinalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os times da semi final ainda não foram definidos!.
        /// </summary>
        public static string TournamentResultService_RegisterFinal_Validation_SemiFinalsNotFound {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterFinal_Validation_SemiFinalsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os times das quartas de final ainda não foram definidos!.
        /// </summary>
        public static string TournamentResultService_RegisterSemiFinals_Validation_QuarterFinalsNotFound {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterSemiFinals_Validation_QuarterFinalsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os times da final ainda não foram definidos!.
        /// </summary>
        public static string TournamentResultService_RegisterWinner_Validation_FinalNotFound {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterWinner_Validation_FinalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time não localizado!.
        /// </summary>
        public static string TournamentResultService_RegisterWinner_Validation_TeamNotFound {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterWinner_Validation_TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O vencedor do torneio precisa ser um time registrado na final!.
        /// </summary>
        public static string TournamentResultService_RegisterWinner_Validation_WinnerInvalid {
            get {
                return ResourceManager.GetString("TournamentResultService_RegisterWinner_Validation_WinnerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o ID do time!.
        /// </summary>
        public static string TournamentResultService_Validation_Required_TeamId {
            get {
                return ResourceManager.GetString("TournamentResultService_Validation_Required_TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informa o ID do torneio!.
        /// </summary>
        public static string TournamentResultService_Validation_Required_TournamentId {
            get {
                return ResourceManager.GetString("TournamentResultService_Validation_Required_TournamentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torneio não localizado!
        ///.
        /// </summary>
        public static string TournamentResultService_Validation_TournamentNotFound {
            get {
                return ResourceManager.GetString("TournamentResultService_Validation_TournamentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O time já foi registrado neste torneio!.
        /// </summary>
        public static string TournamentService_CreateOrUpdateAsync_Validation_TeamAlreadRegistered {
            get {
                return ResourceManager.GetString("TournamentService_CreateOrUpdateAsync_Validation_TeamAlreadRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um torneio cadastrado com este nome!.
        /// </summary>
        public static string TournamentService_CreateOrUpdateAsync_Validation_UniqueTournamentName {
            get {
                return ResourceManager.GetString("TournamentService_CreateOrUpdateAsync_Validation_UniqueTournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torneio não localizado!.
        /// </summary>
        public static string TournamentService_RegisterTeam_Validation_TournamentNotFound {
            get {
                return ResourceManager.GetString("TournamentService_RegisterTeam_Validation_TournamentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o ID do registro!.
        /// </summary>
        public static string Validation_Required_Id {
            get {
                return ResourceManager.GetString("Validation_Required_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível validar todas as informações, por favor, tente novamente!.
        /// </summary>
        public static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
    }
}
