//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nibo.SpaceJam.Infraestructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nibo.SpaceJam.Infraestructure.Resources.WebAPI", typeof(WebAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time não localizado!.
        /// </summary>
        public static string TeamsController_GetAsync_NotFound {
            get {
                return ResourceManager.GetString("TeamsController_GetAsync_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O torneio ainda não possui resultados!.
        /// </summary>
        public static string TournamentResultsController_GetResultAsync_NotFound {
            get {
                return ResourceManager.GetString("TournamentResultsController_GetResultAsync_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A final deste torneio ainda não foi definida!.
        /// </summary>
        public static string TournamentResultsController_GetResultForFinalAsync_NotFound {
            get {
                return ResourceManager.GetString("TournamentResultsController_GetResultForFinalAsync_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As quartas de final deste torneio ainda não foram definidas!.
        /// </summary>
        public static string TournamentResultsController_GetResultForQuarterFinalsAsync_NotFound {
            get {
                return ResourceManager.GetString("TournamentResultsController_GetResultForQuarterFinalsAsync_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A semi final deste torneio ainda não foi definida!.
        /// </summary>
        public static string TournamentResultsController_GetResultForSemiFinalsAsync_NotFound {
            get {
                return ResourceManager.GetString("TournamentResultsController_GetResultForSemiFinalsAsync_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O torneio ainda não possui um ganhador!.
        /// </summary>
        public static string TournamentResultsController_GetWinnerAsync_NotFound {
            get {
                return ResourceManager.GetString("TournamentResultsController_GetWinnerAsync_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torneio não localizado!.
        /// </summary>
        public static string TournamentsController_GetAsync_NotFound {
            get {
                return ResourceManager.GetString("TournamentsController_GetAsync_NotFound", resourceCulture);
            }
        }
    }
}
